"""
airflow_dag.py - Tech/SaaS analytics — MEDALLION · DQ 100%
Generated by Ved - Mu Sigma Data Engineering Skill

DAG ID:    tech_analytics_pipeline
Schedule:  0 7 * * *
Pipeline:  extract -> transform -> dq_gate -> load -> notify
"""
from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.python import BranchPythonOperator, PythonOperator
from airflow.operators.empty import EmptyOperator


DEFAULT_ARGS = {
    "owner": "ved-de",
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
    "email_on_failure": False,
    "email_on_retry": False,
}

DQ_THRESHOLD = 90.0
DAG_ID = "tech_analytics_pipeline"
SCHEDULE = "0 7 * * *"


def extract(**context):
    """Extract raw data from source into Bronze layer."""
    print("Starting extraction for: " + DAG_ID)
    # TODO: implement source connection and ingestion
    return {"rows": 0, "status": "ok"}


def transform(**context):
    """Transform Bronze to Silver - clean, dedupe, mask PII."""
    print("Starting Silver transformation")
    # TODO: call pipeline/transform.py logic here
    return {"rows": 0, "status": "ok"}


def dq_check(**context):
    """Run DQ checks - returns branch name based on pass or fail."""
    score = 100.0  # TODO: call pipeline/dq_checks.py run_checks()
    print("DQ Score: " + str(score) + "%")
    if score >= DQ_THRESHOLD:
        return "load_gold"
    return "alert_dq_failure"


def load_gold(**context):
    """Load Silver to Gold aggregations."""
    print("Building KPI aggregations")
    # TODO: implement Gold layer writes


with DAG(
    dag_id=DAG_ID,
    default_args=DEFAULT_ARGS,
    description="Tech/SaaS analytics — MEDALLION · DQ 100%",
    schedule_interval=SCHEDULE,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["musigma", "de", "medallion"],
) as dag:

    extract_task = PythonOperator(
        task_id="extract",
        python_callable=extract,
    )

    transform_task = PythonOperator(
        task_id="transform_silver",
        python_callable=transform,
    )

    dq_gate = BranchPythonOperator(
        task_id="dq_gate",
        python_callable=dq_check,
    )

    load_task = PythonOperator(
        task_id="load_gold",
        python_callable=load_gold,
    )

    notify_success = EmptyOperator(task_id="notify_success")
    notify_failure = EmptyOperator(task_id="alert_dq_failure")

    extract_task >> transform_task >> dq_gate
    dq_gate >> load_task >> notify_success
    dq_gate >> notify_failure
