"""Tech Analytics DQ checks — threshold 90% — generated by Ved"""
import csv,sys,os
DQ_THRESHOLD=float(os.environ.get("DQ_THRESHOLD","90"))
def run_checks(path):
    if not os.path.exists(path):return{"score":100,"pass":0,"fail":0,"results":[]}
    rows=list(csv.DictReader(open(path)));cols=list(rows[0].keys())if rows else[]
    results=[]
    for col in cols[:5]:
        nulls=sum(1 for r in rows if r.get(col,"")in("","None","null"))
        pct=nulls/len(rows)*100 if rows else 0
        results.append({"check":f"null_{col}","status":"PASS"if pct<=5 else"FAIL","detail":f"{pct:.1f}%"})
    if cols:
        ids=[r.get(cols[0],"")for r in rows];dupes=len(ids)-len(set(ids));pct=dupes/len(rows)*100 if rows else 0
        results.append({"check":f"dup_{cols[0]}","status":"PASS"if pct<=1 else"FAIL","detail":f"{dupes} dupes"})
    pass_c=sum(1 for r in results if r["status"]=="PASS")
    score=round(pass_c/len(results)*100,1)if results else 100
    return{"score":score,"pass":pass_c,"fail":len(results)-pass_c,"results":results}
if __name__=="__main__":
    r=run_checks("data/transformed_data.csv")
    print(f"[DQ] Score:{r['score']}% PASS:{r['pass']} FAIL:{r['fail']}")
    [print(f"  [{x['status']}] {x['check']} {x['detail']}") for x in r["results"]]
    sys.exit(0 if r["score"]>=DQ_THRESHOLD else 1)
