"""
dq_checks.py
Data Quality Validation — Generated by Ved · Mu Sigma DE Skill
DQ threshold: configurable via DQ_THRESHOLD env var (default: 90%)
Exit code 0 = PASS, 1 = FAIL (pipeline gate)
"""
import csv
import sys
import os


DQ_THRESHOLD = float(os.environ.get("DQ_THRESHOLD", "90"))
MAX_NULL_PCT = 5.0
MAX_DUPE_PCT = 1.0


def check_null_rate(rows, col, max_pct=None):
    """Check null rate for a column against threshold."""
    max_pct = max_pct or MAX_NULL_PCT
    null_count = sum(
        1 for r in rows
        if r.get(col, "") in ("", "None", "null", "NULL")
    )
    pct = (null_count / len(rows) * 100) if rows else 0.0
    status = "PASS" if pct <= max_pct else "FAIL"
    return {
        "check": f"null_rate_{col}",
        "category": "Completeness",
        "status": status,
        "detail": f"{pct:.1f}% nulls (threshold {max_pct}%)"
    }


def check_duplicates(rows, key_col, max_pct=None):
    """Check duplicate rate for a key column."""
    max_pct = max_pct or MAX_DUPE_PCT
    all_ids = [r.get(key_col, "") for r in rows]
    dup_count = len(all_ids) - len(set(all_ids))
    pct = (dup_count / len(rows) * 100) if rows else 0.0
    status = "PASS" if pct <= max_pct else "FAIL"
    return {
        "check": f"duplicate_{key_col}",
        "category": "Uniqueness",
        "status": status,
        "detail": f"{dup_count} duplicates ({pct:.1f}%)"
    }


def run_checks(data_path):
    """
    Run all DQ checks on the transformed Silver CSV.

    Returns:
        dict with score, pass, warn, fail counts, and results list
    """
    if not os.path.exists(data_path):
        print(f"[DQ] No data at {data_path} — skipping checks")
        return {"score": 100, "pass": 0, "warn": 0, "fail": 0, "results": []}

    with open(data_path, newline="") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        print("[DQ] Empty file — skipping checks")
        return {"score": 100, "pass": 0, "warn": 0, "fail": 0, "results": []}

    cols = list(rows[0].keys())
    results = []

    # Null checks on first 5 columns
    for col in cols[:5]:
        results.append(check_null_rate(rows, col))

    # Duplicate check on primary key (first column)
    if cols:
        results.append(check_duplicates(rows, cols[0]))

    pass_count = sum(1 for r in results if r["status"] == "PASS")
    fail_count = sum(1 for r in results if r["status"] == "FAIL")
    warn_count = 0
    total = len(results)
    score = round((pass_count / total * 100), 1) if total else 100.0

    return {
        "score": score,
        "pass": pass_count,
        "warn": warn_count,
        "fail": fail_count,
        "results": results
    }


if __name__ == "__main__":
    result = run_checks("data/transformed_data.csv")

    print(f"\n[DQ] Score: {result['score']}%")
    print(f"[DQ] PASS: {result['pass']} | WARN: {result['warn']} | FAIL: {result['fail']}")
    print()

    for r in result["results"]:
        print(f"  [{r['status']:4}] {r['check']:<35} {r['detail']}")

    print()
    if result["score"] < DQ_THRESHOLD:
        print(f"[DQ] FAIL — {result['score']}% < threshold {DQ_THRESHOLD}%")
        print("[DQ] Pipeline gate: BLOCKED")
        sys.exit(1)
    else:
        print(f"[DQ] PASS — {result['score']}% >= threshold {DQ_THRESHOLD}%")
        print("[DQ] Pipeline gate: APPROVED")
        sys.exit(0)
