"""Tech Analytics Silver transforms + PII masking — generated by Ved"""
import hashlib,csv
def sha256(v): return hashlib.sha256(v.encode()).hexdigest() if v else ""
def transform(src,dst,pii_cols=None,null_rules=None):
    pii_cols=pii_cols or [];null_rules=null_rules or {}
    rows=list(csv.DictReader(open(src)));seen=set();silver=[]
    for r in rows:
        r={k.strip().lower().replace(" ","_"):v for k,v in r.items()}
        for col,default in null_rules.items():
            if col in r and r[col] in ("","None","null"):r[col]=default
        for col in pii_cols:
            if col in r:r[col+"_hashed"]=sha256(r.pop(col))
        key=tuple(r.values())
        if key not in seen:seen.add(key);silver.append(r)
    if silver:
        with open(dst,"w",newline="") as f:
            w=csv.DictWriter(f,fieldnames=silver[0].keys());w.writeheader();w.writerows(silver)
    print(f"[TRANSFORM] {len(rows)} -> {len(silver)} rows (PII masked: {pii_cols})")
    return len(silver)
