"""
transform.py
Silver Layer Transformation — Generated by Ved · Mu Sigma DE Skill
"""
import hashlib
import csv


def sha256_hash(value):
    """SHA256 hash a string value (PII masking)."""
    if not value:
        return ""
    return hashlib.sha256(value.encode()).hexdigest()


def normalise_columns(row):
    """Standardise column names to snake_case lowercase."""
    return {
        k.strip().lower().replace(" ", "_"): v
        for k, v in row.items()
    }


def fill_nulls(row, null_rules):
    """Apply null-fill rules: {column: default_value}."""
    for col, default in null_rules.items():
        if col in row and row[col] in ("", "None", "null", "NULL"):
            row[col] = default
    return row


def mask_pii(row, pii_cols):
    """SHA256-hash PII columns, rename to col_hashed."""
    for col in pii_cols:
        if col in row:
            row[col + "_hashed"] = sha256_hash(row.pop(col))
    return row


def transform(source_path, dest_path, pii_cols=None, null_rules=None):
    """
    Run Bronze -> Silver transformation.

    Args:
        source_path: Path to raw Bronze CSV
        dest_path:   Path to write Silver CSV
        pii_cols:    List of columns to SHA256 mask
        null_rules:  Dict of {column: fill_value} for null handling

    Returns:
        Number of Silver rows written
    """
    pii_cols = pii_cols or []
    null_rules = null_rules or {}

    with open(source_path, newline="") as f:
        rows = list(csv.DictReader(f))

    seen = set()
    silver = []

    for row in rows:
        row = normalise_columns(row)
        row = fill_nulls(row, null_rules)
        row = mask_pii(row, pii_cols)

        # Deduplication
        key = tuple(row.values())
        if key not in seen:
            seen.add(key)
            silver.append(row)

    removed = len(rows) - len(silver)
    print(f"[TRANSFORM] {len(rows):,} raw -> {len(silver):,} silver rows ({removed} removed)")

    if silver:
        with open(dest_path, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=silver[0].keys())
            writer.writeheader()
            writer.writerows(silver)
        print(f"[TRANSFORM] Written to: {dest_path}")

    return len(silver)


if __name__ == "__main__":
    transform(
        source_path="data/raw_data.csv",
        dest_path="data/transformed_data.csv",
        pii_cols=[],
        null_rules={}
    )
